// <auto-generated />
using AcmeWidgetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcmeWidgetApp.Migrations
{
    [DbContext(typeof(AcmeWidgetDBContext))]
    partial class AcmeWidgetDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcmeWidgetApp.Models.Registration.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activity");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            ActivityName = "Board game tournament",
                            Description = "A team-wide board game or card game tournament for some in-office fun. Includes prizes!"
                        },
                        new
                        {
                            ActivityId = 2,
                            ActivityName = "Rock Climbing",
                            Description = "test 2"
                        },
                        new
                        {
                            ActivityId = 3,
                            ActivityName = "Escape room",
                            Description = "Escape rooms can simulate office collaboration – they build the same leadership skills, teamwork, logic, and patience. No wonder they have become a popular team building exercise!"
                        },
                        new
                        {
                            ActivityId = 4,
                            ActivityName = "Scavenger hunt",
                            Description = "Scavenger Hunt Anywhere challenges you to a series of questions that you must answer correctly and in time in order to win! This is a great way to focus on skills related to communications, problem solving, strategy and the need to be creative. This event also covers the history of Old Montreal and can be customized to meet the needs of your company"
                        },
                        new
                        {
                            ActivityId = 5,
                            ActivityName = "Mud Racing",
                            Description = "Get your unique mudding experience! Enjoy this awesome off-road racing experience, compete against other mudder truckers and win! Simple controls, a variety of obstacles to pass, awesome cars and extreme tuning!"
                        });
                });

            modelBuilder.Entity("AcmeWidgetApp.Models.Registration.ParticipantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ParticipantInfo");
                });

            modelBuilder.Entity("AcmeWidgetApp.Models.Registration.ParticipantInfo", b =>
                {
                    b.HasOne("AcmeWidgetApp.Models.Registration.Activity", "ActivityList")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
